package com.lextr.semanticlayer.util;

import com.lextr.semanticlayer.exception.SemanticLayerException;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.DefaultResourceLoader;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class SQLQueryLoaderUtilTest {

    @Test
    void loadsRegistryQueriesFromProperties() {
        SQLQueryLoaderUtil loader = new SQLQueryLoaderUtil(new DefaultResourceLoader());

        String schemaQuery = loader.getQuery("schema_registry.find_all");
        String schemaByCodeQuery = loader.getQuery("schema_registry.find_by_code");
        String connectionQuery = loader.getQuery("connection_registry.find_all");
        String connectionByIdQuery = loader.getQuery("connection_registry.find_by_id");
        String insertDraftObjectQuery = loader.getQuery("object_registration.insert_draft_object");
        String insertAttributeQuery = loader.getQuery("object_registration.insert_attribute");
        String updateObjectClassificationQuery = loader.getQuery("object_registration.update_object_classification");
        String updateAttributeClassificationQuery = loader.getQuery("object_registration.update_attribute_classification");
        String insertAttributeAccessGrantWriteQuery = loader.getQuery("object_registration.insert_attribute_access_grant");
        String updateAttributeAccessGrantStatusQuery = loader.getQuery("object_registration.update_attribute_access_grant_status");
        String insertWorkflowTaskQuery = loader.getQuery("object_registration.insert_workflow_task");
        String insertMetadataChangeHistoryQuery = loader.getQuery("object_registration.insert_metadata_change_history");
        String insertRelationshipQuery = loader.getQuery("relationship_registration.insert_relationship");
        String updateRelationshipProjectionSyncQuery = loader.getQuery("relationship_registration.update_neo4j_projection_sync");
        String insertFilterLookupQuery = loader.getQuery("filter_lookup_registration.insert_lookup");
        String certifyFilterLookupQuery = loader.getQuery("filter_lookup_registration.certify_lookup");
        String insertFilterLookupWorkflowTaskQuery = loader.getQuery("filter_lookup_registration.insert_workflow_task");
        String insertFilterLookupMetadataChangeHistoryQuery = loader.getQuery("filter_lookup_registration.insert_metadata_change_history");
        String governancePolicyPresetByCodeQuery = loader.getQuery("governance_policy_preset.find_by_code");
        String classificationListQuery = loader.getQuery("classification_ref.find_all");
        String classificationByCodeQuery = loader.getQuery("classification_ref.find_by_code");
        String attributeAccessGrantQuery = loader.getQuery("attribute_access_grant.find_by_attribute");
        String governanceHistoryByEntityQuery = loader.getQuery("governance_history.find_by_entity");
        String effectiveFilterLookupListQuery = loader.getQuery("filter_lookup_effective_review.find_all");
        String effectiveFilterLookupByCodeQuery = loader.getQuery("filter_lookup_effective_review.find_lookup_by_code");
        String manualFilterLookupPreviewQuery = loader.getQuery("filter_lookup_effective_review.find_manual_values_by_lookup");
        String sqlFilterLookupPreviewQuery = loader.getQuery("filter_lookup_effective_review.find_sql_values_template");
        String filterLookupValueCountQuery = loader.getQuery("filter_lookup_effective_review.count_values_by_lookup");
        String staleFilterLookupValueCountQuery = loader.getQuery("filter_lookup_effective_review.count_stale_values_by_lookup");
        String filterLookupExecutionLogInsertQuery = loader.getQuery("filter_lookup_exec_log.insert_execution");
        String objectListQuery = loader.getQuery("object_exposure.find_all");
        String objectByIdQuery = loader.getQuery("object_exposure.find_by_id");
        String objectBySchemaAndCodeQuery = loader.getQuery("object_exposure.find_by_schema_and_code");
        String attributeByObjectIdQuery = loader.getQuery("object_exposure.find_attributes_by_object_id");
        String objectAccessAuditInsertQuery = loader.getQuery("object_exposure.insert_access_audit");

        assertTrue(schemaQuery.contains("schema_cd"));
        assertTrue(schemaQuery.contains("client_id"));
        assertTrue(schemaQuery.contains("effective_schema_nm"));
        assertTrue(schemaQuery.contains(":lifecycle_status_cd"));
        assertTrue(schemaByCodeQuery.contains(":schema_cd"));
        assertTrue(connectionQuery.contains("connection_id"));
        assertTrue(connectionQuery.contains("client_id"));
        assertTrue(connectionQuery.contains("effective_connection_nm"));
        assertTrue(connectionQuery.contains(":engine_cd"));
        assertTrue(connectionQuery.contains(":is_active_flg"));
        assertTrue(connectionByIdQuery.contains(":connection_id"));
        assertFalse(connectionQuery.contains("secrets_ref"));
        assertTrue(insertDraftObjectQuery.contains("INSERT INTO meta.object_catalog"));
        assertTrue(insertDraftObjectQuery.contains(":object_cd"));
        assertTrue(insertDraftObjectQuery.contains("lifecycle_status_cd"));
        assertTrue(insertAttributeQuery.contains("INSERT INTO meta.attribute_catalog"));
        assertTrue(insertAttributeQuery.contains(":taxonomy_jurisdiction_cd"));
        assertTrue(insertAttributeQuery.contains(":pk_flg"));
        assertTrue(insertAttributeQuery.contains(":fk_flg"));
        assertTrue(insertAttributeQuery.contains(":nullable_flg"));
        assertTrue(updateObjectClassificationQuery.contains("UPDATE meta.object_catalog"));
        assertTrue(updateObjectClassificationQuery.contains("data_classification_cd = :data_classification_cd"));
        assertTrue(updateObjectClassificationQuery.contains("client_id = :client_id"));
        assertTrue(updateObjectClassificationQuery.contains(":object_id"));
        assertTrue(updateAttributeClassificationQuery.contains("UPDATE meta.attribute_catalog a"));
        assertTrue(updateAttributeClassificationQuery.contains("masking_policy_cd = :masking_policy_cd"));
        assertTrue(updateAttributeClassificationQuery.contains("ai_exposure_cd = :ai_exposure_cd"));
        assertTrue(updateAttributeClassificationQuery.contains("a.attribute_cd = :attribute_cd"));
        assertTrue(insertAttributeAccessGrantWriteQuery.contains("INSERT INTO meta.attribute_access_grant"));
        assertTrue(insertAttributeAccessGrantWriteQuery.contains(":grant_scope_cd"));
        assertTrue(insertAttributeAccessGrantWriteQuery.contains(":grant_status_cd"));
        assertTrue(updateAttributeAccessGrantStatusQuery.contains("UPDATE meta.attribute_access_grant"));
        assertTrue(updateAttributeAccessGrantStatusQuery.contains("WHERE client_id = :client_id AND id = :id"));
        assertTrue(updateAttributeAccessGrantStatusQuery.contains(":approved_ts"));
        assertTrue(insertWorkflowTaskQuery.contains("INSERT INTO wkfl.workflow_task"));
        assertTrue(insertWorkflowTaskQuery.contains(":task_status_cd"));
        assertTrue(insertMetadataChangeHistoryQuery.contains("INSERT INTO meta.metadata_change_history"));
        assertTrue(insertMetadataChangeHistoryQuery.contains(":change_summary_txt"));
        assertTrue(insertRelationshipQuery.contains("INSERT INTO meta.semantic_relationship_catalog"));
        assertTrue(insertRelationshipQuery.contains(":relationship_cd"));
        assertTrue(insertRelationshipQuery.contains(":parent_object_cd"));
        assertTrue(insertRelationshipQuery.contains(":child_attribute_cd"));
        assertTrue(insertRelationshipQuery.contains("is_cross_engine_flg"));
        assertTrue(updateRelationshipProjectionSyncQuery.contains("UPDATE meta.semantic_relationship_catalog"));
        assertTrue(updateRelationshipProjectionSyncQuery.contains(":neo4j_synced_ts"));
        assertTrue(updateRelationshipProjectionSyncQuery.contains("WHERE relationship_cd = :relationship_cd"));
        assertTrue(insertFilterLookupQuery.contains("INSERT INTO meta.semantic_filter_lookup"));
        assertTrue(insertFilterLookupQuery.contains(":lookup_cd"));
        assertTrue(insertFilterLookupQuery.contains(":review_period_days_override"));
        assertTrue(insertFilterLookupQuery.contains("governance_status_cd"));
        assertTrue(insertFilterLookupQuery.contains("next_review_due_dt"));
        assertTrue(certifyFilterLookupQuery.contains("UPDATE meta.semantic_filter_lookup"));
        assertTrue(certifyFilterLookupQuery.contains(":health_status_cd"));
        assertTrue(certifyFilterLookupQuery.contains(":last_certified_ts"));
        assertTrue(certifyFilterLookupQuery.contains(":last_certified_by"));
        assertTrue(certifyFilterLookupQuery.contains(":next_review_due_dt"));
        assertTrue(certifyFilterLookupQuery.contains("WHERE client_id = :client_id AND lookup_cd = :lookup_cd"));
        assertTrue(insertFilterLookupWorkflowTaskQuery.contains("INSERT INTO wkfl.workflow_task"));
        assertTrue(insertFilterLookupWorkflowTaskQuery.contains(":entity_ref"));
        assertTrue(insertFilterLookupWorkflowTaskQuery.contains(":submitted_ts"));
        assertTrue(insertFilterLookupMetadataChangeHistoryQuery.contains("INSERT INTO meta.metadata_change_history"));
        assertTrue(insertFilterLookupMetadataChangeHistoryQuery.contains(":changed_ts"));
        assertTrue(insertFilterLookupMetadataChangeHistoryQuery.contains("CAST(:old_value_json AS jsonb)"));
        assertTrue(governancePolicyPresetByCodeQuery.contains("FROM governance.policy_preset"));
        assertTrue(governancePolicyPresetByCodeQuery.contains(":policy_cd"));
        assertTrue(governancePolicyPresetByCodeQuery.contains(":policy_scope_cd"));
        assertTrue(governancePolicyPresetByCodeQuery.contains(":as_of_dt"));
        assertTrue(classificationListQuery.contains("FROM meta.data_classification_ref"));
        assertTrue(classificationListQuery.contains("classification_rank_nbr"));
        assertTrue(classificationByCodeQuery.contains("data_classification_cd = :data_classification_cd"));
        assertTrue(attributeAccessGrantQuery.contains("FROM meta.attribute_access_grant"));
        assertTrue(attributeAccessGrantQuery.contains(":client_id"));
        assertTrue(attributeAccessGrantQuery.contains(":schema_cd"));
        assertTrue(attributeAccessGrantQuery.contains(":object_cd"));
        assertTrue(attributeAccessGrantQuery.contains(":attribute_cd"));
        assertTrue(attributeAccessGrantQuery.contains(":grant_status_cd"));
        assertTrue(governanceHistoryByEntityQuery.contains("FROM meta.metadata_change_history mch"));
        assertTrue(governanceHistoryByEntityQuery.contains(":client_id"));
        assertTrue(governanceHistoryByEntityQuery.contains(":entity_type_cd"));
        assertTrue(governanceHistoryByEntityQuery.contains(":entity_ref"));
        assertTrue(governanceHistoryByEntityQuery.contains(":change_type_cd"));
        assertTrue(governanceHistoryByEntityQuery.contains("EXISTS (SELECT 1 FROM wkfl.workflow_task wt"));
        assertTrue(effectiveFilterLookupListQuery.contains("FROM meta.semantic_filter_lookup"));
        assertTrue(effectiveFilterLookupListQuery.contains(":client_id"));
        assertTrue(effectiveFilterLookupListQuery.contains(":governance_status_cd"));
        assertTrue(effectiveFilterLookupListQuery.contains(":health_status_cd"));
        assertTrue(effectiveFilterLookupListQuery.contains(":lifecycle_status_cd"));
        assertTrue(effectiveFilterLookupListQuery.contains("ORDER BY lookup_cd"));
        assertTrue(effectiveFilterLookupByCodeQuery.contains("FROM meta.semantic_filter_lookup"));
        assertTrue(effectiveFilterLookupByCodeQuery.contains(":client_id"));
        assertTrue(effectiveFilterLookupByCodeQuery.contains(":lookup_cd"));
        assertTrue(effectiveFilterLookupByCodeQuery.contains("review_period_days_override"));
        assertTrue(effectiveFilterLookupByCodeQuery.contains("health_status_cd"));
        assertTrue(effectiveFilterLookupByCodeQuery.contains("last_certified_ts"));
        assertTrue(effectiveFilterLookupByCodeQuery.contains("next_review_due_dt"));
        assertTrue(effectiveFilterLookupByCodeQuery.contains("created_ts"));
        assertTrue(manualFilterLookupPreviewQuery.contains("FROM meta.filter_lookup_value flv"));
        assertTrue(manualFilterLookupPreviewQuery.contains("JOIN meta.semantic_filter_lookup sfl ON sfl.lookup_cd = flv.lookup_cd"));
        assertTrue(manualFilterLookupPreviewQuery.contains(":client_id"));
        assertTrue(manualFilterLookupPreviewQuery.contains(":lookup_cd"));
        assertTrue(manualFilterLookupPreviewQuery.contains("flv.lifecycle_status_cd IN ('ACTIVE','ANTICIPATED')"));
        assertTrue(manualFilterLookupPreviewQuery.contains("anticipated_dt"));
        assertTrue(manualFilterLookupPreviewQuery.contains("ORDER BY CASE flv.lifecycle_status_cd"));
        assertTrue(sqlFilterLookupPreviewQuery.contains("SELECT DISTINCT :lookup_cd AS lookup_cd"));
        assertTrue(sqlFilterLookupPreviewQuery.contains("CAST(%1$s AS varchar(100)) AS value_cd"));
        assertTrue(sqlFilterLookupPreviewQuery.contains("FROM %2$s"));
        assertTrue(sqlFilterLookupPreviewQuery.contains("WHERE %3$s"));
        assertTrue(sqlFilterLookupPreviewQuery.contains("LIMIT :max_output_rows"));
        assertTrue(filterLookupValueCountQuery.contains("FROM meta.filter_lookup_value"));
        assertTrue(filterLookupValueCountQuery.contains(":client_id"));
        assertTrue(filterLookupValueCountQuery.contains(":lookup_cd"));
        assertTrue(filterLookupValueCountQuery.contains("JOIN meta.semantic_filter_lookup sfl ON sfl.lookup_cd = flv.lookup_cd"));
        assertTrue(filterLookupValueCountQuery.contains("COUNT(*) AS value_count"));
        assertTrue(filterLookupValueCountQuery.contains("flv.lifecycle_status_cd IN ('ACTIVE','ANTICIPATED')"));
        assertTrue(filterLookupValueCountQuery.contains("GROUP BY flv.lookup_cd, sfl.client_id"));
        assertTrue(staleFilterLookupValueCountQuery.contains("FROM meta.filter_lookup_value"));
        assertTrue(staleFilterLookupValueCountQuery.contains(":client_id"));
        assertTrue(staleFilterLookupValueCountQuery.contains(":lookup_cd"));
        assertTrue(staleFilterLookupValueCountQuery.contains("COUNT(*) AS stale_value_count"));
        assertTrue(staleFilterLookupValueCountQuery.contains("flv.lifecycle_status_cd = 'INACTIVE_IN_SOURCE'"));
        assertTrue(staleFilterLookupValueCountQuery.contains("GROUP BY flv.lookup_cd, sfl.client_id"));
        assertTrue(filterLookupExecutionLogInsertQuery.contains("INSERT INTO meta.filter_lookup_exec_log"));
        assertTrue(filterLookupExecutionLogInsertQuery.contains(":lookup_cd"));
        assertTrue(filterLookupExecutionLogInsertQuery.contains(":executed_by"));
        assertTrue(filterLookupExecutionLogInsertQuery.contains(":phase1_duration_ms"));
        assertTrue(filterLookupExecutionLogInsertQuery.contains(":phase1_row_count"));
        assertTrue(filterLookupExecutionLogInsertQuery.contains(":phase1_cache_hit_flg"));
        assertTrue(filterLookupExecutionLogInsertQuery.contains(":execution_strategy_used_cd"));
        assertTrue(filterLookupExecutionLogInsertQuery.contains(":result_status_cd"));
        assertTrue(filterLookupExecutionLogInsertQuery.contains("RETURNING id, lookup_cd, executed_by, executed_ts"));
        assertTrue(objectListQuery.contains("FROM meta.object_catalog"));
        assertTrue(objectListQuery.contains("effective_object_nm"));
        assertTrue(objectListQuery.contains("data_classification_cd"));
        assertTrue(objectListQuery.contains("pii_flg"));
        assertTrue(objectListQuery.contains("confidential_flg"));
        assertTrue(objectListQuery.contains(":schema_cd"));
        assertTrue(objectListQuery.contains(":lifecycle_status_cd"));
        assertTrue(objectByIdQuery.contains(":object_id"));
        assertTrue(objectBySchemaAndCodeQuery.contains(":schema_cd"));
        assertTrue(objectBySchemaAndCodeQuery.contains(":object_cd"));
        assertTrue(objectBySchemaAndCodeQuery.contains("effective_object_nm"));
        assertTrue(attributeByObjectIdQuery.contains("FROM meta.attribute_catalog"));
        assertTrue(attributeByObjectIdQuery.contains("effective_attribute_nm"));
        assertTrue(attributeByObjectIdQuery.contains("a.data_classification_cd"));
        assertTrue(attributeByObjectIdQuery.contains("a.masking_policy_cd"));
        assertTrue(attributeByObjectIdQuery.contains("a.ai_exposure_cd"));
        assertTrue(attributeByObjectIdQuery.contains("meta.attribute_logical_name_override"));
        assertTrue(attributeByObjectIdQuery.contains("override_status_cd = 'APPROVED'"));
        assertTrue(attributeByObjectIdQuery.contains("pk_flg"));
        assertTrue(attributeByObjectIdQuery.contains("fk_flg"));
        assertTrue(attributeByObjectIdQuery.contains("nullable_flg"));
        assertTrue(attributeByObjectIdQuery.contains(":object_id"));
        assertTrue(objectAccessAuditInsertQuery.contains("INSERT INTO meta.metadata_change_history"));
        assertTrue(objectAccessAuditInsertQuery.contains(":entity_type_cd"));
        assertTrue(objectAccessAuditInsertQuery.contains(":change_reason_txt"));
    }

    @Test
    void failsWhenQueryKeyMissing() {
        SQLQueryLoaderUtil loader = new SQLQueryLoaderUtil(new DefaultResourceLoader());

        assertThrows(SemanticLayerException.class, () -> loader.getQuery("missing.query"));
    }
}
